# Generated by Django 4.2.25 on 2025-12-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealerprofile",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="dealerprofile",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="dealerprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="dealerprofile",
            name="website",
        ),
        migrations.AddField(
            model_name="dealerprofile",
            name="gst_document",
            field=models.FileField(blank=True, null=True, upload_to="dealer_docs/gst/"),
        ),
        migrations.AddField(
            model_name="dealerprofile",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dealerprofile",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="dealer_docs/id/"),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="company_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="dealerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
