# Generated by Django 4.2.25 on 2025-12-17 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cars", "0002_remove_dealerprofile_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
