# Generated by Django 4.2.25 on 2025-12-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_dealerreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerreview",
            name="dealer_reply",
            field=models.TextField(blank=True),
        ),
    ]
