# Generated by Django 4.2.25 on 2025-12-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_dealerreview_dealer_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerprofile",
            name="admin_message",
            field=models.TextField(
                blank=True, help_text="Message shown to dealer regarding verification"
            ),
        ),
    ]
